hayra/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('volunteers.urls')),
    path('admin/', admin.site.urls),
]

volunteers/urls.py
from django.urls import path

from . import views

app_name = 'volunteers'
urlpatterns = [
	path('', views.volunteers, name='volunteers'),
	path('register/', views.register, name='register'),
	path('message/', views.message, name='message')
]

volunteers/models.py
from django.db import models

TITLE_CHOICES = (
	('Событийный волонтер', 'Событийный волонтер'),
	('Волонтер-донор', 'Волонтер-донор'),
	('Волонтер общественной безопасности', 'Волонтер общественной безопасности'),
	('Медиа-волонтер', 'Медиа-волонтер'),
	('Волонтер помощи страдающим паническими атаками', 'Волонтер помощи страдающим паническими атаками'),
	('Волонтеры финансовой помощи', 'Волонтеры финансовой помощи'),
)

class Volunteer(models.Model):
	name = models.CharField('Имя', max_length = 120)
	phone = models.CharField('Телефон', max_length = 120)
	role = models.CharField('Роль', max_length=120, choices=TITLE_CHOICES)
	date = models.DateTimeField('Дата добавления', auto_now_add = True)

	def __str__(self):
		return self.name

volunteers/forms.py
from django import forms

from .models import Volunteer

class PostForm(forms.ModelForm):
    class Meta:
        model = Volunteer
        fields = ('name', 'phone', 'role')

volunteers/views.py
from django.shortcuts import redirect, render
from .forms import PostForm

from .models import Volunteer

def volunteers(request):
	if not request.user.is_authenticated:
		return redirect('/register')
	else:
		volunteer_list = Volunteer.objects.order_by('-date')
		context = {'volunteer_list': volunteer_list}
	return render(request, 'volunteers/volunteers.html', context)

def register(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save()
			post.save()
			return redirect('/message')
	else:
		form = PostForm()
	return render(request, 'volunteers/register.html', {'form': form})

def message(request):
	return render(request, 'volunteers/message.html')

volunteers/templates/volunteers/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Регистрация волонтеров</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'volunteers/bootstrap/css/bootstrap.min.css' %}">
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  	<a class="navbar-brand" href="/admin">Админ-панель</a>
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="navbar-toggler-icon"></span>
  	</button>

  	<div class="collapse navbar-collapse" id="navbar1">
    	<ul class="navbar-nav mr-auto">
  		{% if request.user.is_authenticated %}
		    <li class="nav-item active">
      		<a class="nav-link" href="{% url 'volunteers:volunteers' %}">Волонтеры <span class="sr-only">(current)</span></a>
    		</li>
			{% endif %}

		    <li class="nav-item active">
		    	<a class="nav-link" href="{% url 'volunteers:register' %}">Регистрация</a>
		    </li>
    	</ul>
    	<!-- <form class="form-inline my-2 my-lg-0">
      		<input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search">
      		<button class="btn btn-outline-info my-2 my-sm-0" type="submit">Найти</button>
    	</form> -->
  	</div>
</nav>

<div class="container">
	<div class="row justify-content-center">
	  <div class="col-xl-12">
	  	<br>
			{% block content %}
			{% endblock %}
		</div>
	</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'volunteers/bootstrap/js/bootstrap.min.js' %}"></script>

</body>
</html>

volunteers/templates/volunteers/message.html
{% extends 'volunteers/base.html' %}

{% block content %}
	<h3>Вы теперь волонтер!</h3>
{% endblock %}

volunteers/templates/volunteers/register.html
{% extends 'volunteers/base.html' %}

{% block content %}

<h5><b>Заполните форму</b></h5>
<form method="POST" class="post-form">{% csrf_token %}
  <div class="form-group">
    <input type="text" class="form-control" id="name" name="name" placeholder="Ваше имя">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" id="phone" name="phone" placeholder="Телефон">
  </div>
  <div class="form-group">
    <label>
      <input type="radio" name="role" value="Событийный волонтер"> <b>1. Событийный волонтер (эвент-волонтер)</b> - участник крупных событий, акций, а также иных мероприятий проводимых БО "Хайра".
    </label>
    <label>
      <input type="radio" name="role" value="Волонтер-донор"> <b>2. Волонтер-донор</b> - человек, готовый оказать посильную помощь в решении вопросов донорства крови, проводить просветительскую работу, и, если позволяет здоровье, при необходимости сам стать донором.
    </label>
    <label>
      <input type="radio" name="role" value="Волонтер общественной безопасности"> <b>3. Волонтер общественной безопасности</b> - добровольческая деятельность, направленная на помощь службам экстренного реагирования в профилактике и ликвидации последствий чрезвычайных ситуаций, помощь в организации обеспечения безопасности на массовых событиях, поиске пропавших людей, содействие интернет-безопасности и т.д.
    </label>
    <label>
      <input type="radio" name="role" value="Медиа-волонтер"> <b>4. Медиа-волонтер</b> - человек, способный применить свои знания и навыки для того, чтобы рассказать о волонтёрстве другим. Это фотографы, журналисты,дизайнеры, люди, популярные в соц.сетях, готовые помочь в распространении информации.
    </label>
    <label>
      <input type="radio" name="role" value="Волонтер помощи страдающим паническими атаками"> <b>5. Волонтер помощи страдающим паническими атаками</b> - доброволец,  который сам переборол недуг, способный поделиться собственным опытом, оказать любую психологическую поддержку.
    </label>
    <label>
      <input type="radio" name="role" value="Волонтеры финансовой помощи"> <b>6. Волонтеры финансовой помощи</b> - доброволец, оказывающий безвозмездную финансово-материальную поддержку. Участвующий в подготовке программ по повышению финансовой грамотности.
    </label>
  </div>
  <button type="submit" class="save btn btn-primary">Я волонтер!</button>
</form>

{% endblock %}

volunteers/templates/volunteers/volunteers.html
{% extends 'volunteers/base.html' %}

{% block content %}

<h5><b>Таблица волонтеров</b></h5>
<div class="table-responsive">
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Имя</th>
				<th scope="col">Телефон</th>
				<th scope="col">Роль</th>
				<th scope="col">Регистрация</th>
			</tr>
		</thead>
		<tbody>
			{% for volunteer in volunteer_list %}
			<tr>
				<th scope="row">{{ volunteer.name }}</th>
				<th>{{ volunteer.phone }}</th>
				<th>{{ volunteer.role }}</th>
				<th>{{ volunteer.date }}</th>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

{% endblock %}